try {
    console.log(naoexisto);
} catch(err) {
    console.log(err)
}